### ISSUE TITLE
Minimum targets: IE10 and ES5?

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser3#4]
It would be nice to drop (or never add) support for IE9/XDR and JavaScript prior to ES5.

**Comment by photonstorm** [comment]
We just can't - too many agencies rely on Phaser for their client work, and too many clients still demand IE9 support. I also don't believe IE9 specifically adds that much overhead to the API. I'm struggling to even think of any IE9 'hacks' we've had to put in there. The issue would come with transpiling ES6 of course. But before we get to that stage we're finishing off integrating the new renderer into Phaser 2.

**Comment by Swinkid** [comment]
I'd like to see it dropped, but I agree with Photon - Regardless that only around 1% of people still use IE9.

**Comment by pnstickne** [comment]
Wish denied :}

**Comment by photonstorm** [comment]
@Swinkid depends on the site, we've clients that have around 15% IE9 use still.

**Comment by englercj** [comment]
The only place where IE9 hacks came in a lot for us was in the resource-loader. There is about 2x as much loading code to accommodate IE9 weirdness. Rendering though (via canvas) is pretty straight forward.

**Comment by pnstickne** [comment]
For me, the real thing I want to be able to do is rely upon the ES5 Array functions - and to ensure that these are available to anyone who is running Phaser 3.

This 'guarantee' could also be done with shim methods, of course.

**Comment by englercj** [comment]
Why? The array functions are stupid slow compared to a normal loop :)
